fix(ci): update time of files changed since last cache build
Signed-off-by: Nils Ponsard <nils.ponsard@inria.fr>

diff --git a/.github/workflows/build-cache.yml b/.github/workflows/build-cache.yml
--- a/.github/workflows/build-cache.yml
+++ b/.github/workflows/build-cache.yml
@@ -95,27 +95,36 @@ jobs:
         if: steps.clear-cache.outputs.result == 'true'
         run: echo "FALLBACK_KEY=none" >> "$GITHUB_ENV"
 
-      # Allows to reuse more cache
-      - name: Touch file time to commits time
-        if: steps.should-skip.outputs.result != 'true'
-        # https://stackoverflow.com/questions/21735435/git-clone-changes-file-modification-time
-        run: |
-          git ls-tree -r --name-only HEAD | while read filename; do
-            unixtime=$(git log -1 --format="%at" -- "${filename}")
-            touchtime=$(date -d @$unixtime +'%Y%m%d%H%M.%S')
-            touch -t ${touchtime} "${filename}"
-          done
-
       - name: Cache with post-job cleanup
         if: steps.should-skip.outputs.result != 'true'
         uses: gacts/run-and-post-run@81b6ce503cde93862cec047c54652e45c5dca991 # v1
         with:
           run: |
-            cache-thing pull -f build -f /home/runner/.cargo/git -f /home/runner/.cargo/registry --prefix global --fallback-key ${FALLBACK_KEY} || true
+            cache-thing pull -f /home/runner/metadata -f build -f /home/runner/.cargo/git -f /home/runner/.cargo/registry --prefix global --fallback-key ${FALLBACK_KEY} || true
 
           post: |
             export  RUST_LOG=trace
             cache-thing clean --prefix global || true
+
+      # Allows to reuse more cache
+      - name: Touch file time to commits time
+        if: steps.should-skip.outputs.result != 'true'
+        # https://stackoverflow.com/questions/21735435/git-clone-changes-file-modification-time
+        run: |
+          if [ -f /home/runner/metadata/cache-ref ]; then
+            git ls-tree -r --name-only HEAD | while read filename; do
+              unixtime=$(git log -1 --format="%at" -- "${filename}")
+              touchtime=$(date -d @$unixtime +'%Y%m%d%H%M.%S')
+              touch -t ${touchtime} "${filename}"
+            done
+
+            # Treat all files modified after the cached commit as "changed", by touching them.
+            git diff --name-only $(cat /home/runner/metadata/cache-ref) | while read filename; do
+              touch "${filename}"
+            done
+          else
+             echo "/home/runner/metadata/cache-ref not found, skipping step"
+          fi
 
       - id: get_toolchain
         if: steps.should-skip.outputs.result != 'true'
@@ -153,9 +162,12 @@ jobs:
       - name: show sccache stats
         run: sccache --show-stats
 
+      - name: update ref of nightly
+        run: git rev-parse HEAD > /home/runner/metadata/cache-ref
+
       - name: "Save cache of nightly run"
         if: steps.should-skip.outputs.result != 'true'
         env:
           RUST_LOG: trace
         run: |
-          cache-thing push -f build -f /home/runner/.cargo/git -f /home/runner/.cargo/registry --prefix global --fixed-key nightly --only-fixed-key || true
+          cache-thing push -f /home/runner/metadata -f build -f /home/runner/.cargo/git -f /home/runner/.cargo/registry --prefix global --fixed-key nightly --only-fixed-key || true
diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -212,7 +212,7 @@ jobs:
         with:
           run: |
             export  RUST_LOG=trace
-            cache-thing pull -f build -f /home/runner/.cargo/git -f /home/runner/.cargo/registry --prefix global --suffix "${{ matrix.partition }}" --fallback-key nightly || true
+            cache-thing pull -f /home/runner/metadata -f build -f /home/runner/.cargo/git -f /home/runner/.cargo/registry --prefix global --suffix "${{ matrix.partition }}" --fallback-key nightly || true
 
           post: |
             export  RUST_LOG=trace
@@ -337,11 +337,21 @@ jobs:
         if: steps.should-skip.outputs.result != 'true' && runner.environment == 'self-hosted'
         # https://stackoverflow.com/questions/21735435/git-clone-changes-file-modification-time
         run: |
+          if [ -f /home/runner/metadata/cache-ref ]; then
             git ls-tree -r --name-only HEAD | while read filename; do
               unixtime=$(git log -1 --format="%at" -- "${filename}")
               touchtime=$(date -d @$unixtime +'%Y%m%d%H%M.%S')
               touch -t ${touchtime} "${filename}"
             done
+
+            # Treat all files modified after the cached commit as "changed", by touching them.
+            git diff --name-only $(cat /home/runner/metadata/cache-ref) | while read filename; do
+              touch "${filename}"
+            done
+          else
+             echo "/home/runner/metadata/cache-ref not found, skipping step"
+          fi
+
       - name: "start sccache daemon"
         if: steps.should-skip.outputs.result != 'true' && runner.environment == 'self-hosted'
         # work around https://github.com/ninja-build/ninja/issues/2052
