feat(ci): add self hosted runners
Signed-off-by: Nils Ponsard <nils.ponsard@inria.fr>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -9,7 +9,7 @@ on:
   merge_group:
   schedule:
     # run every morning at 3:17am
-    - cron: '17 3 * * *'
+    - cron: "17 3 * * *"
 
 concurrency:
   group: ${{ github.head_ref || github.run_id }}-build
@@ -83,7 +83,11 @@ jobs:
 
   build:
     needs: check-labels
-    runs-on: ubuntu-24.04
+    runs-on:
+      group: Ariel
+      # TODO: update the image of the nodes in the other center
+      labels: ["saclay"]
+
     # Ignore the PR labels in nightly builds.
     if: ${{ github.event_name == 'schedule' || needs.check-labels.outputs.label != 'ci-build:skip' }}
 
@@ -97,14 +101,33 @@ jobs:
       # newest standard library. It may also need to be aligned with the clang
       # version which Xtensa provides.
       CLANG_PATH: /usr/bin/clang-18
+      CACHE_THING_LOCATION: /cache/cache-thing
+      RUSTC_WRAPPER: sccache
+      # CARGO_NET_GIT_FETCH_WITH_CLI: true
+      SCCACHE_DIR: /cache/sccache
+      SCCACHE_CACHE_SIZE: 128G
 
     strategy:
       fail-fast: true
       matrix:
-        partition: ["1/20", "2/20", "3/20", "4/20", "5/20", "6/20", "7/20", "8/20", "9/20", "10/20", "11/20", "12/20", "13/20", "14/20", "15/20", "16/20", "17/20", "18/20", "19/20", "20/20"]
+        partition:
+          [
+            "1/10",
+            "2/10",
+            "3/10",
+            "4/10",
+            "5/10",
+            "6/10",
+            "7/10",
+            "8/10",
+            "9/10",
+            "10/10",
+          ]
 
     steps:
+
       - name: Free up space
+        if: runner.environment != 'self-hosted'
         run: |
           sudo rm -rf \
             /opt/ghc \
@@ -120,12 +143,17 @@ jobs:
 
       - name: Check out repository code
         uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
+        with:
+          # we need to access the Main branch for the cache
+          fetch-depth: 0
 
+      # - name: reset git-cache update barrier
+      #   run: pkill -f -SIGUSR1 /usr/local/bin/git-cache-daemon | true
       - name: Get git tree hash
         id: get-tree-hash
         run: |
-            git rev-parse HEAD^{tree} > .tree-hash
-            echo "hash=$(cat .tree-hash)" >> $GITHUB_OUTPUT
+          git rev-parse HEAD^{tree} > .tree-hash
+          echo "hash=$(cat .tree-hash)" >> $GITHUB_OUTPUT
 
       - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
         id: result-cache
@@ -139,6 +167,19 @@ jobs:
           result="result=${{ steps.result-cache.outputs.cache-hit == 'true' }}"
           echo "${result}"
           echo "${result}" >> $GITHUB_OUTPUT
+
+      # Allows us to clean up even if build fails
+      - name: Cache with post-job cleanup
+        if: steps.should-skip.outputs.result != 'true' && runner.environment == 'self-hosted'
+        uses: gacts/run-and-post-run@v1
+        with:
+          run: |
+            export  RUST_LOG=trace
+            cache-thing pull -f build -f /home/runner/.cargo/git -f /home/runner/.cargo/registry --prefix global --suffix "${{ matrix.partition }}" --fallback-key nightly || true
+
+          post: |
+            export  RUST_LOG=trace
+            cache-thing clean --prefix global --suffix "${{ matrix.partition }}" || true
 
       - name: "limit build unless nightly build"
         if: github.event_name != 'schedule' && steps.should-skip.outputs.result != 'true'
@@ -185,7 +226,7 @@ jobs:
         run: echo "toolchain=$(scripts/rust-toolchain.sh)" >> $GITHUB_OUTPUT
 
       - name: Install nightly toolchain
-        if: steps.should-skip.outputs.result != 'true'
+        if: steps.should-skip.outputs.result != 'true' && runner.environment != 'self-hosted'
         uses: dtolnay/rust-toolchain@master
         with:
           toolchain: ${{ steps.get_toolchain.outputs.toolchain }}
@@ -195,7 +236,7 @@ jobs:
           components: rust-src, rustfmt
 
       - name: Install stable toolchain
-        if: steps.should-skip.outputs.result != 'true'
+        if: steps.should-skip.outputs.result != 'true' && runner.environment != 'self-hosted'
         # configure MSRV here:
         uses: dtolnay/rust-toolchain@1.85
         with:
@@ -205,7 +246,7 @@ jobs:
           components: rust-src, rustfmt
 
       - name: Install Rust for Xtensa
-        if: steps.should-skip.outputs.result != 'true' && (github.event_name == 'schedule' || env.NEEDS_XTENSA_TOOLCHAIN == '1')
+        if: steps.should-skip.outputs.result != 'true' && (github.event_name == 'schedule' || env.NEEDS_XTENSA_TOOLCHAIN == '1') && runner.environment != 'self-hosted'
         # No tag yet after https://github.com/esp-rs/xtensa-toolchain/pull/38 (will probably be @v1.5.5)
         uses: esp-rs/xtensa-toolchain@main
         with:
@@ -215,19 +256,19 @@ jobs:
           export: false
 
       - name: rust cache
-        if: steps.should-skip.outputs.result != 'true'
         uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2
+        if: steps.should-skip.outputs.result != 'true' && runner.environment != 'self-hosted'
         with:
           key: "${{ matrix.partition }}"
 
       - name: Install laze
         uses: taiki-e/install-action@6cc14f7f2f4b3129aff07a8b071d2d4f2733465d # v2
-        if: steps.should-skip.outputs.result != 'true'
+        if: steps.should-skip.outputs.result != 'true' && runner.environment != 'self-hosted'
         with:
           tool: laze@0.1
 
       - name: "installing prerequisites"
-        if: steps.should-skip.outputs.result != 'true'
+        if: steps.should-skip.outputs.result != 'true' && runner.environment != 'self-hosted'
         run: sudo apt-get install ninja-build gcc-arm-none-eabi gcc-riscv64-unknown-elf
 
       - name: "Show installed versions"
@@ -249,6 +290,11 @@ jobs:
           sha256sum /usr/lib/llvm-*/lib/clang/*/include/stdint.h
           true
 
+      - name: "start sccache daemon"
+        if: steps.should-skip.outputs.result != 'true' && runner.environment == 'self-hosted'
+        # work around https://github.com/ninja-build/ninja/issues/2052
+        run: sccache --start-server || true
+
       - name: "ariel-os compilation test (default toolchain)"
         if: steps.should-skip.outputs.result != 'true'
         run: |
@@ -263,12 +309,16 @@ jobs:
         run: |
           mv build build.tmp && rm -rf build.tmp &
 
-      # nightly build, nightly toolchain
+      # nightly build, nightly toolchain, no cache for this one
       # (disabling xtensa here as it gets built by the default toolchain build above)
       - name: "ariel-os compilation test (nightly toolchain)"
         if: github.event_name == 'schedule' && steps.should-skip.outputs.result != 'true'
         run: |
           CONFIG_WIFI_NETWORK='test' CONFIG_WIFI_PASSWORD='password' laze build -DCARGO_ARGS+='--locked' --global --partition hash:${{ matrix.partition }} --select nightly --disable xtensa
+
+      - name: show sccache stats
+        if: runner.environment == 'self-hosted'
+        run: sccache --show-stats
 
   build-success:
     if: ${{ always() }}
@@ -292,3 +342,123 @@ jobs:
           access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
           message: "The nightly build [failed](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})."
           server: "matrix.org"
+  # build cache on each garm node
+  build-cache:
+    runs-on:
+      group: Ariel
+      labels: ["${{ matrix.node }}"]
+
+    # Only run for nightly builds
+    if: ${{ github.event_name == 'schedule' }}
+
+    strategy:
+      matrix:
+        # Add each CI nodes here
+        node: ["tribe-ariel-os-ci1", "tribe-ariel-os-ci2"]
+    env:
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # clang-sys and thus bindgen is sensitive to multiple installed versions
+      # around, see eg. https://github.com/rust-lang/rust-bindgen/issues/2682
+      #
+      # CLANG_PATH should be set to the most recent clang installed, no matter
+      # what /usr/bin/clang is, for some parts of the code will go for the
+      # newest standard library. It may also need to be aligned with the clang
+      # version which Xtensa provides.
+      CLANG_PATH: /usr/bin/clang-18
+      CACHE_THING_LOCATION: /cache/cache-thing
+      RUSTC_WRAPPER: sccache
+      # CARGO_NET_GIT_FETCH_WITH_CLI: true
+      SCCACHE_DIR: /cache/sccache
+      SCCACHE_CACHE_SIZE: 128G
+
+      # local bucket, but we should put that as a GH secret anyway
+      S3_KEY_ID: GK8eac3f2e561d911c3653f0d4
+      S3_SECRET_KEY: 8b16840d766a023d60ce6e0c1d248795043a4b578bd1edc1e3f6c04ca88c3327
+      S3_BUCKET: cache-thing
+      S3_ENDPOINT: http://10.0.0.1:3900
+      S3_REGION: garage
+
+    steps:
+      - name: Check out repository code
+        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
+        with:
+          # we need to access the Main branch for the cache
+          fetch-depth: 0
+
+      # - name: reset git-cache update barrier
+      #   run: pkill -f -SIGUSR1 /usr/local/bin/git-cache-daemon | true
+
+      - name: Get git tree hash
+        id: get-tree-hash
+        run: |
+          git rev-parse HEAD^{tree} > .tree-hash
+          echo "hash=$(cat .tree-hash)" >> $GITHUB_OUTPUT
+
+      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
+        id: result-cache
+        with:
+          path: .tree-hash
+          key: success-${{ steps.get-tree-hash.outputs.hash }}-${{ matrix.node }}-${{ github.event_name == 'schedule' && 'full' || needs.check-labels.outputs.label }}
+
+      - name: Whether to skip next steps
+        id: should-skip
+        run: |
+          result="result=${{ steps.result-cache.outputs.cache-hit == 'true' }}"
+          echo "${result}"
+          echo "${result}" >> $GITHUB_OUTPUT
+
+      - name: Cache with post-job cleanup
+        if: steps.should-skip.outputs.result != 'true'
+        uses: gacts/run-and-post-run@v1
+        with:
+          run: |
+            export  RUST_LOG=trace
+            cache-thing pull -f build -f /home/runner/.cargo/git -f /home/runner/.cargo/registry --prefix global --fallback-key nightly || true
+
+          post: |
+            export  RUST_LOG=trace
+            cache-thing clean --prefix global || true
+
+      - id: get_toolchain
+        if: steps.should-skip.outputs.result != 'true'
+        run: echo "toolchain=$(scripts/rust-toolchain.sh)" >> $GITHUB_OUTPUT
+
+      - name: "Show installed versions"
+        run: |
+          set -x
+          set +e
+          env
+          llvm-config --libs
+          cargo version
+          laze --version
+          arm-none-eabi-gcc --version
+          clang --version
+          rustup show
+          cat ${ESPUP_EXPORT_FILE:-~/export-esp.sh}
+          (. ${ESPUP_EXPORT_FILE:-~/export-esp.sh}; xtensa-esp32s3-elf-gcc --version)
+          set +x
+          # Check which alternative versions are installed
+          IFS=":"; for p in $PATH; do ls $p/llvm-config-* $p/clang-* 2>/dev/null; done
+          sha256sum /usr/lib/llvm-*/lib/clang/*/include/stdint.h
+          true
+
+      - name: "start sccache daemon"
+        if: steps.should-skip.outputs.result != 'true'
+        # work around https://github.com/ninja-build/ninja/issues/2052
+        run: sccache --start-server || true
+
+      - name: "ariel-os compilation test (default toolchain)"
+        if: steps.should-skip.outputs.result != 'true'
+        run: |
+          CONFIG_WIFI_NETWORK='test' CONFIG_WIFI_PASSWORD='password' laze build -DCARGO_ARGS+='--locked' --global
+
+      - name: show sccache stats
+        if: runner.environment == 'self-hosted'
+        run: sccache --show-stats
+
+      - name: "Save cache of nightly run"
+        if: steps.should-skip.outputs.result != 'true'
+        env:
+          RUST_LOG: trace
+        run: |
+          cache-thing push -f build -f /home/runner/.cargo/git -f /home/runner/.cargo/registry --prefix global --fixed-key nightly --only-fixed-key || true
